# Generated by Django 2.1.2 on 2018-10-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyoperations',
            name='successful_charge',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='historyoperations',
            name='successful_recharge',
            field=models.BooleanField(null=True),
        ),
    ]
