# Generated by Django 2.1.2 on 2018-10-09 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_auto_20181007_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historyoperations',
            name='modified',
        ),
        migrations.AlterField(
            model_name='clientwalletaccount',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_wallets', to='wallet.Client'),
        ),
        migrations.AlterField(
            model_name='tradewalletaccount',
            name='trade',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trade_wallets', to='wallet.Trade'),
        ),
    ]
